# Generated by Django 5.1 on 2024-08-09 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='card_tag',
            field=models.CharField(default='Estrela', max_length=100),
            preserve_default=False,
        ),
    ]
